from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Any, Dict, Optional

import requests

REFERENCE_DOMAINS = [
    "company investor relations",
    "company annual report / SEC filing",
    "company product documentation",
    "company trust / security / privacy page",
    "Yahoo Finance",
    "Investing.com",
    "Bloomberg",
    "FactSet",
    "Morningstar",
    "Fidelity research",
    "reputable news coverage",
    "optional Xquik public X signal context when XQUIK_API_KEY is configured",
]


@dataclass
class ProviderConfig:
    provider: str
    model: str
    vendor: str
    ticker: str = ""
    website: str = ""
    competitors: str = ""
    sec_cik: str = ""
    depth: str = "exhaustive"


class ProviderError(RuntimeError):
    pass


def _api_key(provider: str) -> str:
    mapping = {
        "openai": "OPENAI_API_KEY",
        "anthropic": "ANTHROPIC_API_KEY",
        "gemini": "GEMINI_API_KEY",
        "perplexity": "PERPLEXITY_API_KEY",
    }
    env = mapping.get(provider)
    if not env:
        raise ProviderError(f"Unsupported provider: {provider}")
    key = os.getenv(env) or (os.getenv("GOOGLE_API_KEY") if provider == "gemini" else "")
    if not key:
        raise ProviderError(f"Missing API key environment variable for provider '{provider}'. Expected {env}.")
    return key


def build_section_prompt(config: ProviderConfig, agent: str, title: str, context_markdown: str = "") -> str:
    source_text = "\n".join(f"- {domain}" for domain in REFERENCE_DOMAINS)
    return f"""
You are executing VendorIQ's {agent} for an exhaustive vendor due-diligence report.

Vendor: {config.vendor}
Ticker: {config.ticker or 'Not provided'}
Website: {config.website or 'Not provided'}
SEC CIK: {config.sec_cik or 'Not provided'}
Competitors provided by user: {config.competitors or 'Not provided'}
Section title: {title}

Write only Markdown for this section. Do not output HTML, CSS, JavaScript, files, or standalone JSON.

Hard requirements:
- Produce 500+ words of narrative analysis for this section unless reliable public evidence is unavailable.
- Use exhaustive public-source research.
- Every factual claim must include a raw source URL inline while drafting. The orchestrator will convert raw URLs into numbered references.
- Prefer official sources first, then SEC filings, investor relations, product docs, trust/security pages, Yahoo Finance, Investing.com, Bloomberg, FactSet, Morningstar, Fidelity research, reputable news, and optional Xquik public X signals where configured.
- Treat Xquik public X signal context as anecdotal. Use it for market perception, customer feedback, partner activity, incidents, product announcements, and forward-looking chatter. Do not use it as primary proof for financial metrics, contracts, certifications, litigation, private customer claims, or representative sentiment.
- Do not invent product names, customers, certifications, executive biographies, financial metrics, contracts, architecture, or partnerships.
- If information is unavailable, write: Not found in public sources reviewed.
- Include Markdown tables where useful.
- For business model, revenue model, products, architecture, product moat, and differentiation, be specific and detailed.
- For executive leadership, include leader names, roles, prior experience, and strategic relevance, with evidence URLs.

Preferred evidence classes to search:
{source_text}

Additional context Markdown already generated by the orchestrator, if relevant:
{context_markdown}
""".strip()


def _post_json(url: str, headers: Dict[str, str], payload: Dict[str, Any], timeout: int = 120) -> Dict[str, Any]:
    response = requests.post(url, headers=headers, json=payload, timeout=timeout)
    response.raise_for_status()
    return response.json()


def call_openai(config: ProviderConfig, prompt: str) -> str:
    key = _api_key("openai")
    model = config.model or "gpt-4.1"
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a meticulous evidence-backed vendor due-diligence analyst. Return Markdown only."},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
    }
    data = _post_json("https://api.openai.com/v1/chat/completions", {"Authorization": f"Bearer {key}", "Content-Type": "application/json"}, payload)
    return data["choices"][0]["message"]["content"]


def call_perplexity(config: ProviderConfig, prompt: str) -> str:
    key = _api_key("perplexity")
    model = config.model or "sonar-pro"
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a web-research analyst. Return Markdown only and include raw URLs for all facts."},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
    }
    data = _post_json("https://api.perplexity.ai/chat/completions", {"Authorization": f"Bearer {key}", "Content-Type": "application/json"}, payload)
    return data["choices"][0]["message"]["content"]


def call_anthropic(config: ProviderConfig, prompt: str) -> str:
    key = _api_key("anthropic")
    model = config.model or "claude-3-5-sonnet-latest"
    payload = {
        "model": model,
        "max_tokens": 6000,
        "temperature": 0.2,
        "messages": [{"role": "user", "content": prompt}],
    }
    data = _post_json(
        "https://api.anthropic.com/v1/messages",
        {"x-api-key": key, "anthropic-version": "2023-06-01", "Content-Type": "application/json"},
        payload,
    )
    content = data.get("content", [])
    return "\n".join(part.get("text", "") for part in content if part.get("type") == "text")


def call_gemini(config: ProviderConfig, prompt: str) -> str:
    key = _api_key("gemini")
    model = config.model or "gemini-2.5-flash"
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={key}"
    payload = {"contents": [{"role": "user", "parts": [{"text": prompt}]}], "generationConfig": {"temperature": 0.2}}
    data = _post_json(url, {"Content-Type": "application/json"}, payload)
    candidates = data.get("candidates", [])
    if not candidates:
        return ""
    parts = candidates[0].get("content", {}).get("parts", [])
    return "\n".join(part.get("text", "") for part in parts)


def generate_section_markdown(config: ProviderConfig, agent: str, title: str, context_markdown: str = "") -> str:
    if config.provider == "offline":
        return _offline_section(agent, title, context_markdown)
    prompt = build_section_prompt(config, agent, title, context_markdown)
    if config.provider == "openai":
        return call_openai(config, prompt)
    if config.provider == "anthropic":
        return call_anthropic(config, prompt)
    if config.provider == "gemini":
        return call_gemini(config, prompt)
    if config.provider == "perplexity":
        return call_perplexity(config, prompt)
    raise ProviderError(f"Unsupported provider: {config.provider}")


def _offline_section(agent: str, title: str, context_markdown: str = "") -> str:
    body = [
        f"## {title}",
        "",
        f"Offline scaffold for `{agent}`. A web-enabled provider is required to generate the 500+ word evidence-backed section, search Yahoo Finance, Investing.com, Bloomberg, FactSet, Morningstar, Fidelity, official filings, product pages, leadership pages, optional Xquik public X signals when configured, and current news sources.",
        "",
        "Not found in public sources reviewed.",
    ]
    if context_markdown and ("Financial" in title or "Xquik" in context_markdown):
        body.append(context_markdown)
    return "\n".join(body) + "\n"
